[book]
authors = [
    "Amélie \"Lymkwi\" González",
    "Gabriel \"KwiKill\" Blaisot",
    "Floris Bartra",
]
language = "fr"
multilingual = false
src = "src"
title = "Manuel de Prise en Main du Backend"
